# Generated by Django 2.0.2 on 2018-02-18 12:36

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BallotEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Meeting.Device')),
            ],
        ),
        migrations.CreateModel(
            name='TokenSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meeting.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meeting.TokenSet')),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='token_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meeting.TokenSet'),
        ),
        migrations.AddField(
            model_name='ballotentry',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Meeting.Token'),
        ),
        migrations.AddField(
            model_name='ballotentry',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meeting.Vote'),
        ),
    ]
