# Generated by Django 2.0.2 on 2018-02-21 23:14

import Meeting.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('has_proxy', models.BooleanField(default=False)),
                ('id', models.PositiveIntegerField(default=Meeting.models.get_new_token_id, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BallotEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('close_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('channel', models.TextField(null=True)),
                ('auth_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meeting.AuthToken')),
            ],
        ),
        migrations.CreateModel(
            name='TokenSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meeting.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('RE', 'Ready'), ('LI', 'Live'), ('CO', 'Counting'), ('TI', 'Needs Tie Breaker'), ('CL', 'Closed')], default='RE', max_length=2)),
                ('token_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meeting.TokenSet')),
            ],
        ),
        migrations.CreateModel(
            name='VoterToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.BooleanField(default=False)),
                ('auth_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meeting.AuthToken')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meeting.Vote'),
        ),
        migrations.AddField(
            model_name='ballotentry',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meeting.Option'),
        ),
        migrations.AddField(
            model_name='ballotentry',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Meeting.VoterToken'),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='token_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meeting.TokenSet'),
        ),
        migrations.AlterUniqueTogether(
            name='ballotentry',
            unique_together={('token', 'option')},
        ),
    ]
