# Generated by Django 2.0.2 on 2018-02-18 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meeting.Vote')),
            ],
        ),
    ]
