# Generated by Django 2.0.2 on 2018-02-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vote',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
