# Generated by Django 2.0.2 on 2018-03-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='close_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
