# Generated by Django 2.0.2 on 2018-02-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0002_auto_20180221_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
