# Generated by Django 2.0.2 on 2018-03-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0002_auto_20180314_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
