# Generated by Django 2.0.2 on 2018-02-18 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0003_auto_20180218_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Meeting.Device'),
        ),
    ]
