# Generated by Django 2.0.2 on 2018-02-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0003_option_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='method',
            field=models.CharField(choices=[('YNA', 'Yes No Abs'), ('STV', 'Single Transferable Vote')], default='STV', max_length=3),
        ),
    ]
