# Generated by Django 2.0.2 on 2018-02-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0005_auto_20180222_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballotentry',
            name='value',
            field=models.SmallIntegerField(default=1),
        ),
    ]
