# Generated by Django 2.0.2 on 2018-02-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0005_auto_20180218_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
